name: super_camera
description: A Flutter plugin used as a base plugin for accessing a device camera. The main goal of
  this plugin is to handle abstracting differences between cameras on different platforms and
  creates an easy way to create more complex camera plugins.
version: 0.0.1
author:
  - Maurice <bmparr2450@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  permission_handler: ^3.0.0

flutter:
  plugin:
    androidPackage: com.example.supercamera
    pluginClass: SuperCameraPlugin
